### ISSUE TITLE
json2tbl leaves extra padding at the end

### ISSUE THREAD

**Issue by nnguyen259** [nnguyen259/KuroTools#14]
currently affecting btlsys, gourmet, condition info and chapter save. shouldn't be a big deal but it's nice to investigate to iron them out finally.

**Comment by TwnKey** [comment]
Ah no sorry, the padded zeros come from the decrypted files. When compiling them json2tbl just don't read them since the files usually end with text which ends with a single 0.
Pic below with the recompiled file at the top and the decrypted file (from korean tables) at the bottom
![image](https://user-images.githubusercontent.com/69110695/183452502-0fbdd029-1940-4ac0-b411-f3f7390908b4.png)

**Comment by nnguyen259** [comment]
Extra padding is for Blowfish encryption. Not a bug
